# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build, Test and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  
    - name: Setup
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
          dotnet-version: 7.0.x

    - name: Build Linux
      shell: bash
      run: |
          # Define some variables for things we need
          tag=$(git describe --tags --abbrev=0)
          release_name="App-$tag-linux-x64"

          # Build everything
          dotnet publish Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --runtime linux-x64 -c Release -o "Linux-release"
          
          tar czvf "Linux-release.tar.gz" "Linux-release"

    - name: Build MacOS
      shell: bash
      run: |
          # Define some variables for things we need
          tag=$(git describe --tags --abbrev=0)
          release_name="App-$tag-osx-x64"

          # Build everything
          dotnet publish Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --runtime osx-x64 -c Release -o "MacOS-release"
          
          tar czvf "MacOS-release.tar.gz" "MacOS-release"


    - name: Build Windows
      shell: bash
      run: |
          # Define some variables for things we need
          tag=$(git describe --tags --abbrev=0)
          release_name="App-$tag-win-x64"

          # Build everything
          dotnet publish Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --runtime win-x64 -c Release -o "Windows-release"
          
          tar czvf "Windows-release.tar.gz" "Windows-release"

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
          files: |
            README.md
            Linux-release.tar.gz
            MacOS-release.tar.gz
            Windows-release.tar.gz
            
          repo-token: ${{ secrets.GITHUB_TOKEN }}
