#Used to automaticly convert our report.md to a pdf 
name: Render report.pdf

on: push

jobs:
  convert_and_upload_pdf:
    runs-on: ubuntu-latest


    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install pandoc
        run:  sudo apt-get install -y pandoc

      - name: install Tex Live
        run: sudo apt-get install -y texlive
      - name: Convert to PDF
        run:  pandoc docs/report.md --resource-path=docs -o docs/2024_itubdsa_group_15_report.pdf

      - name: upload pdf 
        run: |
            git config --global user.name "pdf-uploader"
            git config --global user.email "pdfuploader@pdf.noreply.notreal.com"
            git pull
            git add docs/2024_itubdsa_group_15_report.pdf
            git commit -m "report: Uploaded pdf from report.md"
            git push

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        
 
          
               
