#https://nielsvaneck.com/post/2021-01-31-render-md-mermaid-a-github-action/
#Used to automaticly convert our report.md to a pdf including our mermaid diagrams 

name: Render report.pdf

on: push

jobs:
  render-md-mermaid:
    runs-on: ubuntu-latest


    steps:
      - name: checkout docs
        uses: actions/checkout@v4

      - name: Install pandoc
        run:  sudo apt-get install -y pandoc

      - name: install Tex Live
        run: sudo apt-get install -y texlive
      - name: Convert to PDF
        run:  pandoc report.md -o report.pdf

      - name: upload pdf
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.pdf
               
