#https://nielsvaneck.com/post/2021-01-31-render-md-mermaid-a-github-action/
#Used to automaticly convert our report.md to a pdf including our mermaid diagrams 

name: Render report.pdf

on: push

jobs:
  render-md-mermaid:
    runs-on: ubuntu-latest


    steps:
      - name: checkout 
        uses: actions/checkout@v4

      - name: Install pandoc
      - run:  sudo apt-get install -y pandoc
      
      - name: Convert to PDF
        run:  pandoc report.md -o report.pdf

      - name: upload pdf
        uses: actions/upload-artifact@v3
        with:
          name: report-pdf
          path: docs/
               
